#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppBodegaService.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TripleHBpm3")]
	public partial class EmbarquesAppModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMuestra(Muestra instance);
    partial void UpdateMuestra(Muestra instance);
    partial void DeleteMuestra(Muestra instance);
    partial void InsertMuestraDetalle(MuestraDetalle instance);
    partial void UpdateMuestraDetalle(MuestraDetalle instance);
    partial void DeleteMuestraDetalle(MuestraDetalle instance);
    partial void InsertMuestraDetalleTamaño(MuestraDetalleTamaño instance);
    partial void UpdateMuestraDetalleTamaño(MuestraDetalleTamaño instance);
    partial void DeleteMuestraDetalleTamaño(MuestraDetalleTamaño instance);
    partial void InsertMuestraFoto(MuestraFoto instance);
    partial void UpdateMuestraFoto(MuestraFoto instance);
    partial void DeleteMuestraFoto(MuestraFoto instance);
    partial void InsertProducto(Producto instance);
    partial void UpdateProducto(Producto instance);
    partial void DeleteProducto(Producto instance);
    partial void InsertMuestraCarga(MuestraCarga instance);
    partial void UpdateMuestraCarga(MuestraCarga instance);
    partial void DeleteMuestraCarga(MuestraCarga instance);
    partial void InsertMuestraDetalleColor(MuestraDetalleColor instance);
    partial void UpdateMuestraDetalleColor(MuestraDetalleColor instance);
    partial void DeleteMuestraDetalleColor(MuestraDetalleColor instance);
    partial void InsertTarimasCarga(TarimasCarga instance);
    partial void UpdateTarimasCarga(TarimasCarga instance);
    partial void DeleteTarimasCarga(TarimasCarga instance);
    #endregion
		
		public EmbarquesAppModelDataContext() : 
				base("Data Source=serverdb;Initial Catalog=TripleHBpm3;User ID=sa;Password=Pomodoro92%", mappingSource)
		{
			OnCreated();
		}
		
		public EmbarquesAppModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmbarquesAppModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmbarquesAppModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmbarquesAppModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Muestra> Muestras
		{
			get
			{
				return this.GetTable<Muestra>();
			}
		}
		
		public System.Data.Linq.Table<MuestraDetalle> MuestraDetalles
		{
			get
			{
				return this.GetTable<MuestraDetalle>();
			}
		}
		
		public System.Data.Linq.Table<MuestraDetalleTamaño> MuestraDetalleTamaños
		{
			get
			{
				return this.GetTable<MuestraDetalleTamaño>();
			}
		}
		
		public System.Data.Linq.Table<MuestraFoto> MuestraFotos
		{
			get
			{
				return this.GetTable<MuestraFoto>();
			}
		}
		
		public System.Data.Linq.Table<Producto> Productos
		{
			get
			{
				return this.GetTable<Producto>();
			}
		}
		
		public System.Data.Linq.Table<MuestraCarga> MuestraCargas
		{
			get
			{
				return this.GetTable<MuestraCarga>();
			}
		}
		
		public System.Data.Linq.Table<MuestraDetalleColor> MuestraDetalleColors
		{
			get
			{
				return this.GetTable<MuestraDetalleColor>();
			}
		}
		
		public System.Data.Linq.Table<TarimasCarga> TarimasCargas
		{
			get
			{
				return this.GetTable<TarimasCarga>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Muestra")]
	public partial class Muestra : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Codigo;
		
		private System.Nullable<int> _CodigoCultivo;
		
		private System.Nullable<int> _CodigoTamaño;
		
		private System.Nullable<int> _CodigoColor;
		
		private System.Nullable<int> _Marca;
		
		private int _UnidadesMuestra;
		
		private int _CodigoTipoMuestra;
		
		private System.Nullable<decimal> _Peso;
		
		private System.Nullable<int> _CantidadUnidades;
		
		private System.Nullable<int> _CodigoLoteProceso;
		
		private System.DateTime _Fecha;
		
		private System.Nullable<decimal> _pesoEvaluado;
		
		private System.Nullable<int> _CodigoRecepcionProduce;
		
		private System.Nullable<int> _CodigoMuestraCampo;
		
		private string _CodigoProducto;
		
		private System.Nullable<int> _CodigoTextura;
		
		private System.Nullable<int> _CodigoCarga;
		
		private string _Nota;
		
		private System.Nullable<System.DateTime> _FechaHoraModificacion;
		
		private System.Nullable<int> _CodigoAgricultor;
		
		private string _CodigoPallet;
		
		private string _CodigoHeroku;
		
		private EntitySet<MuestraDetalle> _MuestraDetalles;
		
		private EntitySet<MuestraDetalleTamaño> _MuestraDetalleTamaños;
		
		private EntitySet<MuestraFoto> _MuestraFotos;
		
		private EntitySet<MuestraCarga> _MuestraCargas;
		
		private EntitySet<MuestraDetalleColor> _MuestraDetalleColors;
		
		private EntitySet<TarimasCarga> _TarimasCargas;
		
		private EntityRef<Producto> _Producto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoChanging(int value);
    partial void OnCodigoChanged();
    partial void OnCodigoCultivoChanging(System.Nullable<int> value);
    partial void OnCodigoCultivoChanged();
    partial void OnCodigoTamañoChanging(System.Nullable<int> value);
    partial void OnCodigoTamañoChanged();
    partial void OnCodigoColorChanging(System.Nullable<int> value);
    partial void OnCodigoColorChanged();
    partial void OnMarcaChanging(System.Nullable<int> value);
    partial void OnMarcaChanged();
    partial void OnUnidadesMuestraChanging(int value);
    partial void OnUnidadesMuestraChanged();
    partial void OnCodigoTipoMuestraChanging(int value);
    partial void OnCodigoTipoMuestraChanged();
    partial void OnPesoChanging(System.Nullable<decimal> value);
    partial void OnPesoChanged();
    partial void OnCantidadUnidadesChanging(System.Nullable<int> value);
    partial void OnCantidadUnidadesChanged();
    partial void OnCodigoLoteProcesoChanging(System.Nullable<int> value);
    partial void OnCodigoLoteProcesoChanged();
    partial void OnFechaChanging(System.DateTime value);
    partial void OnFechaChanged();
    partial void OnpesoEvaluadoChanging(System.Nullable<decimal> value);
    partial void OnpesoEvaluadoChanged();
    partial void OnCodigoRecepcionProduceChanging(System.Nullable<int> value);
    partial void OnCodigoRecepcionProduceChanged();
    partial void OnCodigoMuestraCampoChanging(System.Nullable<int> value);
    partial void OnCodigoMuestraCampoChanged();
    partial void OnCodigoProductoChanging(string value);
    partial void OnCodigoProductoChanged();
    partial void OnCodigoTexturaChanging(System.Nullable<int> value);
    partial void OnCodigoTexturaChanged();
    partial void OnCodigoCargaChanging(System.Nullable<int> value);
    partial void OnCodigoCargaChanged();
    partial void OnNotaChanging(string value);
    partial void OnNotaChanged();
    partial void OnFechaHoraModificacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaHoraModificacionChanged();
    partial void OnCodigoAgricultorChanging(System.Nullable<int> value);
    partial void OnCodigoAgricultorChanged();
    partial void OnCodigoPalletChanging(string value);
    partial void OnCodigoPalletChanged();
    partial void OnCodigoHerokuChanging(string value);
    partial void OnCodigoHerokuChanged();
    #endregion
		
		public Muestra()
		{
			this._MuestraDetalles = new EntitySet<MuestraDetalle>(new Action<MuestraDetalle>(this.attach_MuestraDetalles), new Action<MuestraDetalle>(this.detach_MuestraDetalles));
			this._MuestraDetalleTamaños = new EntitySet<MuestraDetalleTamaño>(new Action<MuestraDetalleTamaño>(this.attach_MuestraDetalleTamaños), new Action<MuestraDetalleTamaño>(this.detach_MuestraDetalleTamaños));
			this._MuestraFotos = new EntitySet<MuestraFoto>(new Action<MuestraFoto>(this.attach_MuestraFotos), new Action<MuestraFoto>(this.detach_MuestraFotos));
			this._MuestraCargas = new EntitySet<MuestraCarga>(new Action<MuestraCarga>(this.attach_MuestraCargas), new Action<MuestraCarga>(this.detach_MuestraCargas));
			this._MuestraDetalleColors = new EntitySet<MuestraDetalleColor>(new Action<MuestraDetalleColor>(this.attach_MuestraDetalleColors), new Action<MuestraDetalleColor>(this.detach_MuestraDetalleColors));
			this._TarimasCargas = new EntitySet<TarimasCarga>(new Action<TarimasCarga>(this.attach_TarimasCargas), new Action<TarimasCarga>(this.detach_TarimasCargas));
			this._Producto = default(EntityRef<Producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoCultivo", DbType="Int")]
		public System.Nullable<int> CodigoCultivo
		{
			get
			{
				return this._CodigoCultivo;
			}
			set
			{
				if ((this._CodigoCultivo != value))
				{
					this.OnCodigoCultivoChanging(value);
					this.SendPropertyChanging();
					this._CodigoCultivo = value;
					this.SendPropertyChanged("CodigoCultivo");
					this.OnCodigoCultivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoTamaño", DbType="Int")]
		public System.Nullable<int> CodigoTamaño
		{
			get
			{
				return this._CodigoTamaño;
			}
			set
			{
				if ((this._CodigoTamaño != value))
				{
					this.OnCodigoTamañoChanging(value);
					this.SendPropertyChanging();
					this._CodigoTamaño = value;
					this.SendPropertyChanged("CodigoTamaño");
					this.OnCodigoTamañoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoColor", DbType="Int")]
		public System.Nullable<int> CodigoColor
		{
			get
			{
				return this._CodigoColor;
			}
			set
			{
				if ((this._CodigoColor != value))
				{
					this.OnCodigoColorChanging(value);
					this.SendPropertyChanging();
					this._CodigoColor = value;
					this.SendPropertyChanged("CodigoColor");
					this.OnCodigoColorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marca", DbType="Int")]
		public System.Nullable<int> Marca
		{
			get
			{
				return this._Marca;
			}
			set
			{
				if ((this._Marca != value))
				{
					this.OnMarcaChanging(value);
					this.SendPropertyChanging();
					this._Marca = value;
					this.SendPropertyChanged("Marca");
					this.OnMarcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnidadesMuestra", DbType="Int NOT NULL")]
		public int UnidadesMuestra
		{
			get
			{
				return this._UnidadesMuestra;
			}
			set
			{
				if ((this._UnidadesMuestra != value))
				{
					this.OnUnidadesMuestraChanging(value);
					this.SendPropertyChanging();
					this._UnidadesMuestra = value;
					this.SendPropertyChanged("UnidadesMuestra");
					this.OnUnidadesMuestraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoTipoMuestra", DbType="Int NOT NULL")]
		public int CodigoTipoMuestra
		{
			get
			{
				return this._CodigoTipoMuestra;
			}
			set
			{
				if ((this._CodigoTipoMuestra != value))
				{
					this.OnCodigoTipoMuestraChanging(value);
					this.SendPropertyChanging();
					this._CodigoTipoMuestra = value;
					this.SendPropertyChanged("CodigoTipoMuestra");
					this.OnCodigoTipoMuestraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Peso", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> Peso
		{
			get
			{
				return this._Peso;
			}
			set
			{
				if ((this._Peso != value))
				{
					this.OnPesoChanging(value);
					this.SendPropertyChanging();
					this._Peso = value;
					this.SendPropertyChanged("Peso");
					this.OnPesoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadUnidades", DbType="Int")]
		public System.Nullable<int> CantidadUnidades
		{
			get
			{
				return this._CantidadUnidades;
			}
			set
			{
				if ((this._CantidadUnidades != value))
				{
					this.OnCantidadUnidadesChanging(value);
					this.SendPropertyChanging();
					this._CantidadUnidades = value;
					this.SendPropertyChanged("CantidadUnidades");
					this.OnCantidadUnidadesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoLoteProceso", DbType="Int")]
		public System.Nullable<int> CodigoLoteProceso
		{
			get
			{
				return this._CodigoLoteProceso;
			}
			set
			{
				if ((this._CodigoLoteProceso != value))
				{
					this.OnCodigoLoteProcesoChanging(value);
					this.SendPropertyChanging();
					this._CodigoLoteProceso = value;
					this.SendPropertyChanged("CodigoLoteProceso");
					this.OnCodigoLoteProcesoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pesoEvaluado", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> pesoEvaluado
		{
			get
			{
				return this._pesoEvaluado;
			}
			set
			{
				if ((this._pesoEvaluado != value))
				{
					this.OnpesoEvaluadoChanging(value);
					this.SendPropertyChanging();
					this._pesoEvaluado = value;
					this.SendPropertyChanged("pesoEvaluado");
					this.OnpesoEvaluadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoRecepcionProduce", DbType="Int")]
		public System.Nullable<int> CodigoRecepcionProduce
		{
			get
			{
				return this._CodigoRecepcionProduce;
			}
			set
			{
				if ((this._CodigoRecepcionProduce != value))
				{
					this.OnCodigoRecepcionProduceChanging(value);
					this.SendPropertyChanging();
					this._CodigoRecepcionProduce = value;
					this.SendPropertyChanged("CodigoRecepcionProduce");
					this.OnCodigoRecepcionProduceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoMuestraCampo", DbType="Int")]
		public System.Nullable<int> CodigoMuestraCampo
		{
			get
			{
				return this._CodigoMuestraCampo;
			}
			set
			{
				if ((this._CodigoMuestraCampo != value))
				{
					this.OnCodigoMuestraCampoChanging(value);
					this.SendPropertyChanging();
					this._CodigoMuestraCampo = value;
					this.SendPropertyChanged("CodigoMuestraCampo");
					this.OnCodigoMuestraCampoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoProducto", DbType="NVarChar(20)")]
		public string CodigoProducto
		{
			get
			{
				return this._CodigoProducto;
			}
			set
			{
				if ((this._CodigoProducto != value))
				{
					if (this._Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodigoProductoChanging(value);
					this.SendPropertyChanging();
					this._CodigoProducto = value;
					this.SendPropertyChanged("CodigoProducto");
					this.OnCodigoProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoTextura", DbType="Int")]
		public System.Nullable<int> CodigoTextura
		{
			get
			{
				return this._CodigoTextura;
			}
			set
			{
				if ((this._CodigoTextura != value))
				{
					this.OnCodigoTexturaChanging(value);
					this.SendPropertyChanging();
					this._CodigoTextura = value;
					this.SendPropertyChanged("CodigoTextura");
					this.OnCodigoTexturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoCarga", DbType="Int")]
		public System.Nullable<int> CodigoCarga
		{
			get
			{
				return this._CodigoCarga;
			}
			set
			{
				if ((this._CodigoCarga != value))
				{
					this.OnCodigoCargaChanging(value);
					this.SendPropertyChanging();
					this._CodigoCarga = value;
					this.SendPropertyChanged("CodigoCarga");
					this.OnCodigoCargaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nota", DbType="VarChar(500)")]
		public string Nota
		{
			get
			{
				return this._Nota;
			}
			set
			{
				if ((this._Nota != value))
				{
					this.OnNotaChanging(value);
					this.SendPropertyChanging();
					this._Nota = value;
					this.SendPropertyChanged("Nota");
					this.OnNotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaHoraModificacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaHoraModificacion
		{
			get
			{
				return this._FechaHoraModificacion;
			}
			set
			{
				if ((this._FechaHoraModificacion != value))
				{
					this.OnFechaHoraModificacionChanging(value);
					this.SendPropertyChanging();
					this._FechaHoraModificacion = value;
					this.SendPropertyChanged("FechaHoraModificacion");
					this.OnFechaHoraModificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoAgricultor", DbType="Int")]
		public System.Nullable<int> CodigoAgricultor
		{
			get
			{
				return this._CodigoAgricultor;
			}
			set
			{
				if ((this._CodigoAgricultor != value))
				{
					this.OnCodigoAgricultorChanging(value);
					this.SendPropertyChanging();
					this._CodigoAgricultor = value;
					this.SendPropertyChanged("CodigoAgricultor");
					this.OnCodigoAgricultorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoPallet", DbType="NVarChar(20)")]
		public string CodigoPallet
		{
			get
			{
				return this._CodigoPallet;
			}
			set
			{
				if ((this._CodigoPallet != value))
				{
					this.OnCodigoPalletChanging(value);
					this.SendPropertyChanging();
					this._CodigoPallet = value;
					this.SendPropertyChanged("CodigoPallet");
					this.OnCodigoPalletChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoHeroku", DbType="nvarchar(40)")]
		public string CodigoHeroku
		{
			get
			{
				return this._CodigoHeroku;
			}
			set
			{
				if ((this._CodigoHeroku != value))
				{
					this.OnCodigoHerokuChanging(value);
					this.SendPropertyChanging();
					this._CodigoHeroku = value;
					this.SendPropertyChanged("CodigoHeroku");
					this.OnCodigoHerokuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Muestra_MuestraDetalle", Storage="_MuestraDetalles", ThisKey="Codigo", OtherKey="CodigoMuestra")]
		public EntitySet<MuestraDetalle> MuestraDetalles
		{
			get
			{
				return this._MuestraDetalles;
			}
			set
			{
				this._MuestraDetalles.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Muestra_MuestraDetalleTamaño", Storage="_MuestraDetalleTamaños", ThisKey="Codigo", OtherKey="CodigoMuestra")]
		public EntitySet<MuestraDetalleTamaño> MuestraDetalleTamaños
		{
			get
			{
				return this._MuestraDetalleTamaños;
			}
			set
			{
				this._MuestraDetalleTamaños.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Muestra_MuestraFoto", Storage="_MuestraFotos", ThisKey="Codigo", OtherKey="CodigoMuestra")]
		public EntitySet<MuestraFoto> MuestraFotos
		{
			get
			{
				return this._MuestraFotos;
			}
			set
			{
				this._MuestraFotos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Muestra_MuestraCarga", Storage="_MuestraCargas", ThisKey="Codigo", OtherKey="CodigoMuestra")]
		public EntitySet<MuestraCarga> MuestraCargas
		{
			get
			{
				return this._MuestraCargas;
			}
			set
			{
				this._MuestraCargas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Muestra_MuestraDetalleColor", Storage="_MuestraDetalleColors", ThisKey="Codigo", OtherKey="CodigoMuestra")]
		public EntitySet<MuestraDetalleColor> MuestraDetalleColors
		{
			get
			{
				return this._MuestraDetalleColors;
			}
			set
			{
				this._MuestraDetalleColors.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Muestra_TarimasCarga", Storage="_TarimasCargas", ThisKey="Codigo", OtherKey="CodigoMuestra")]
		public EntitySet<TarimasCarga> TarimasCargas
		{
			get
			{
				return this._TarimasCargas;
			}
			set
			{
				this._TarimasCargas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Muestra", Storage="_Producto", ThisKey="CodigoProducto", OtherKey="ItemCode", IsForeignKey=true)]
		public Producto Producto
		{
			get
			{
				return this._Producto.Entity;
			}
			set
			{
				Producto previousValue = this._Producto.Entity;
				if (((previousValue != value) 
							|| (this._Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Producto.Entity = null;
						previousValue.Muestras.Remove(this);
					}
					this._Producto.Entity = value;
					if ((value != null))
					{
						value.Muestras.Add(this);
						this._CodigoProducto = value.ItemCode;
					}
					else
					{
						this._CodigoProducto = default(string);
					}
					this.SendPropertyChanged("Producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MuestraDetalles(MuestraDetalle entity)
		{
			this.SendPropertyChanging();
			entity.Muestra = this;
		}
		
		private void detach_MuestraDetalles(MuestraDetalle entity)
		{
			this.SendPropertyChanging();
			entity.Muestra = null;
		}
		
		private void attach_MuestraDetalleTamaños(MuestraDetalleTamaño entity)
		{
			this.SendPropertyChanging();
			entity.Muestra = this;
		}
		
		private void detach_MuestraDetalleTamaños(MuestraDetalleTamaño entity)
		{
			this.SendPropertyChanging();
			entity.Muestra = null;
		}
		
		private void attach_MuestraFotos(MuestraFoto entity)
		{
			this.SendPropertyChanging();
			entity.Muestra = this;
		}
		
		private void detach_MuestraFotos(MuestraFoto entity)
		{
			this.SendPropertyChanging();
			entity.Muestra = null;
		}
		
		private void attach_MuestraCargas(MuestraCarga entity)
		{
			this.SendPropertyChanging();
			entity.Muestra = this;
		}
		
		private void detach_MuestraCargas(MuestraCarga entity)
		{
			this.SendPropertyChanging();
			entity.Muestra = null;
		}
		
		private void attach_MuestraDetalleColors(MuestraDetalleColor entity)
		{
			this.SendPropertyChanging();
			entity.Muestra = this;
		}
		
		private void detach_MuestraDetalleColors(MuestraDetalleColor entity)
		{
			this.SendPropertyChanging();
			entity.Muestra = null;
		}
		
		private void attach_TarimasCargas(TarimasCarga entity)
		{
			this.SendPropertyChanging();
			entity.Muestra = this;
		}
		
		private void detach_TarimasCargas(TarimasCarga entity)
		{
			this.SendPropertyChanging();
			entity.Muestra = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MuestraDetalle")]
	public partial class MuestraDetalle : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Codigo;
		
		private int _CodigoDefecto;
		
		private int _Cantidad;
		
		private int _CodigoMuestra;
		
		private int _CodigoSeveridad;
		
		private EntityRef<Muestra> _Muestra;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoChanging(int value);
    partial void OnCodigoChanged();
    partial void OnCodigoDefectoChanging(int value);
    partial void OnCodigoDefectoChanged();
    partial void OnCantidadChanging(int value);
    partial void OnCantidadChanged();
    partial void OnCodigoMuestraChanging(int value);
    partial void OnCodigoMuestraChanged();
    partial void OnCodigoSeveridadChanging(int value);
    partial void OnCodigoSeveridadChanged();
    #endregion
		
		public MuestraDetalle()
		{
			this._Muestra = default(EntityRef<Muestra>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoDefecto", DbType="Int NOT NULL")]
		public int CodigoDefecto
		{
			get
			{
				return this._CodigoDefecto;
			}
			set
			{
				if ((this._CodigoDefecto != value))
				{
					this.OnCodigoDefectoChanging(value);
					this.SendPropertyChanging();
					this._CodigoDefecto = value;
					this.SendPropertyChanged("CodigoDefecto");
					this.OnCodigoDefectoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int NOT NULL")]
		public int Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this.OnCantidadChanging(value);
					this.SendPropertyChanging();
					this._Cantidad = value;
					this.SendPropertyChanged("Cantidad");
					this.OnCantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoMuestra", DbType="Int NOT NULL")]
		public int CodigoMuestra
		{
			get
			{
				return this._CodigoMuestra;
			}
			set
			{
				if ((this._CodigoMuestra != value))
				{
					if (this._Muestra.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodigoMuestraChanging(value);
					this.SendPropertyChanging();
					this._CodigoMuestra = value;
					this.SendPropertyChanged("CodigoMuestra");
					this.OnCodigoMuestraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoSeveridad", DbType="Int NOT NULL")]
		public int CodigoSeveridad
		{
			get
			{
				return this._CodigoSeveridad;
			}
			set
			{
				if ((this._CodigoSeveridad != value))
				{
					this.OnCodigoSeveridadChanging(value);
					this.SendPropertyChanging();
					this._CodigoSeveridad = value;
					this.SendPropertyChanged("CodigoSeveridad");
					this.OnCodigoSeveridadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Muestra_MuestraDetalle", Storage="_Muestra", ThisKey="CodigoMuestra", OtherKey="Codigo", IsForeignKey=true)]
		public Muestra Muestra
		{
			get
			{
				return this._Muestra.Entity;
			}
			set
			{
				Muestra previousValue = this._Muestra.Entity;
				if (((previousValue != value) 
							|| (this._Muestra.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Muestra.Entity = null;
						previousValue.MuestraDetalles.Remove(this);
					}
					this._Muestra.Entity = value;
					if ((value != null))
					{
						value.MuestraDetalles.Add(this);
						this._CodigoMuestra = value.Codigo;
					}
					else
					{
						this._CodigoMuestra = default(int);
					}
					this.SendPropertyChanged("Muestra");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MuestraDetalleTamaño")]
	public partial class MuestraDetalleTamaño : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Codigo;
		
		private int _CodigoMuestra;
		
		private int _CodigoTamaño;
		
		private int _Cantidad;
		
		private System.Nullable<int> _CantidadFueraRango;
		
		private EntityRef<Muestra> _Muestra;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoChanging(int value);
    partial void OnCodigoChanged();
    partial void OnCodigoMuestraChanging(int value);
    partial void OnCodigoMuestraChanged();
    partial void OnCodigoTamañoChanging(int value);
    partial void OnCodigoTamañoChanged();
    partial void OnCantidadChanging(int value);
    partial void OnCantidadChanged();
    partial void OnCantidadFueraRangoChanging(System.Nullable<int> value);
    partial void OnCantidadFueraRangoChanged();
    #endregion
		
		public MuestraDetalleTamaño()
		{
			this._Muestra = default(EntityRef<Muestra>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoMuestra", DbType="Int NOT NULL")]
		public int CodigoMuestra
		{
			get
			{
				return this._CodigoMuestra;
			}
			set
			{
				if ((this._CodigoMuestra != value))
				{
					if (this._Muestra.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodigoMuestraChanging(value);
					this.SendPropertyChanging();
					this._CodigoMuestra = value;
					this.SendPropertyChanged("CodigoMuestra");
					this.OnCodigoMuestraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoTamaño", DbType="Int NOT NULL")]
		public int CodigoTamaño
		{
			get
			{
				return this._CodigoTamaño;
			}
			set
			{
				if ((this._CodigoTamaño != value))
				{
					this.OnCodigoTamañoChanging(value);
					this.SendPropertyChanging();
					this._CodigoTamaño = value;
					this.SendPropertyChanged("CodigoTamaño");
					this.OnCodigoTamañoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int NOT NULL")]
		public int Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this.OnCantidadChanging(value);
					this.SendPropertyChanging();
					this._Cantidad = value;
					this.SendPropertyChanged("Cantidad");
					this.OnCantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadFueraRango", DbType="Int")]
		public System.Nullable<int> CantidadFueraRango
		{
			get
			{
				return this._CantidadFueraRango;
			}
			set
			{
				if ((this._CantidadFueraRango != value))
				{
					this.OnCantidadFueraRangoChanging(value);
					this.SendPropertyChanging();
					this._CantidadFueraRango = value;
					this.SendPropertyChanged("CantidadFueraRango");
					this.OnCantidadFueraRangoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Muestra_MuestraDetalleTamaño", Storage="_Muestra", ThisKey="CodigoMuestra", OtherKey="Codigo", IsForeignKey=true)]
		public Muestra Muestra
		{
			get
			{
				return this._Muestra.Entity;
			}
			set
			{
				Muestra previousValue = this._Muestra.Entity;
				if (((previousValue != value) 
							|| (this._Muestra.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Muestra.Entity = null;
						previousValue.MuestraDetalleTamaños.Remove(this);
					}
					this._Muestra.Entity = value;
					if ((value != null))
					{
						value.MuestraDetalleTamaños.Add(this);
						this._CodigoMuestra = value.Codigo;
					}
					else
					{
						this._CodigoMuestra = default(int);
					}
					this.SendPropertyChanged("Muestra");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MuestraFoto")]
	public partial class MuestraFoto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Codigo;
		
		private int _CodigoMuestra;
		
		private string _NombreArchivo;
		
		private string _Descripcion;
		
		private string _NombreArchivoOriginal;
		
		private string _MimeType;
		
		private byte _TipoArchivo;
		
		private string _CodigoHeroku;
		
		private EntityRef<Muestra> _Muestra;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoChanging(int value);
    partial void OnCodigoChanged();
    partial void OnCodigoMuestraChanging(int value);
    partial void OnCodigoMuestraChanged();
    partial void OnNombreArchivoChanging(string value);
    partial void OnNombreArchivoChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnNombreArchivoOriginalChanging(string value);
    partial void OnNombreArchivoOriginalChanged();
    partial void OnMimeTypeChanging(string value);
    partial void OnMimeTypeChanged();
    partial void OnTipoArchivoChanging(byte value);
    partial void OnTipoArchivoChanged();
    partial void OnCodigoHerokuChanging(string value);
    partial void OnCodigoHerokuChanged();
    #endregion
		
		public MuestraFoto()
		{
			this._Muestra = default(EntityRef<Muestra>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoMuestra", DbType="Int NOT NULL")]
		public int CodigoMuestra
		{
			get
			{
				return this._CodigoMuestra;
			}
			set
			{
				if ((this._CodigoMuestra != value))
				{
					if (this._Muestra.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodigoMuestraChanging(value);
					this.SendPropertyChanging();
					this._CodigoMuestra = value;
					this.SendPropertyChanged("CodigoMuestra");
					this.OnCodigoMuestraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreArchivo", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string NombreArchivo
		{
			get
			{
				return this._NombreArchivo;
			}
			set
			{
				if ((this._NombreArchivo != value))
				{
					this.OnNombreArchivoChanging(value);
					this.SendPropertyChanging();
					this._NombreArchivo = value;
					this.SendPropertyChanged("NombreArchivo");
					this.OnNombreArchivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreArchivoOriginal", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string NombreArchivoOriginal
		{
			get
			{
				return this._NombreArchivoOriginal;
			}
			set
			{
				if ((this._NombreArchivoOriginal != value))
				{
					this.OnNombreArchivoOriginalChanging(value);
					this.SendPropertyChanging();
					this._NombreArchivoOriginal = value;
					this.SendPropertyChanged("NombreArchivoOriginal");
					this.OnNombreArchivoOriginalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MimeType", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string MimeType
		{
			get
			{
				return this._MimeType;
			}
			set
			{
				if ((this._MimeType != value))
				{
					this.OnMimeTypeChanging(value);
					this.SendPropertyChanging();
					this._MimeType = value;
					this.SendPropertyChanged("MimeType");
					this.OnMimeTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoArchivo", DbType="TinyInt NOT NULL")]
		public byte TipoArchivo
		{
			get
			{
				return this._TipoArchivo;
			}
			set
			{
				if ((this._TipoArchivo != value))
				{
					this.OnTipoArchivoChanging(value);
					this.SendPropertyChanging();
					this._TipoArchivo = value;
					this.SendPropertyChanged("TipoArchivo");
					this.OnTipoArchivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoHeroku", DbType="nvarchar(40)")]
		public string CodigoHeroku
		{
			get
			{
				return this._CodigoHeroku;
			}
			set
			{
				if ((this._CodigoHeroku != value))
				{
					this.OnCodigoHerokuChanging(value);
					this.SendPropertyChanging();
					this._CodigoHeroku = value;
					this.SendPropertyChanged("CodigoHeroku");
					this.OnCodigoHerokuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Muestra_MuestraFoto", Storage="_Muestra", ThisKey="CodigoMuestra", OtherKey="Codigo", IsForeignKey=true)]
		public Muestra Muestra
		{
			get
			{
				return this._Muestra.Entity;
			}
			set
			{
				Muestra previousValue = this._Muestra.Entity;
				if (((previousValue != value) 
							|| (this._Muestra.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Muestra.Entity = null;
						previousValue.MuestraFotos.Remove(this);
					}
					this._Muestra.Entity = value;
					if ((value != null))
					{
						value.MuestraFotos.Add(this);
						this._CodigoMuestra = value.Codigo;
					}
					else
					{
						this._CodigoMuestra = default(int);
					}
					this.SendPropertyChanged("Muestra");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Producto")]
	public partial class Producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ItemCode;
		
		private string _ItemName;
		
		private System.Nullable<short> _ItmsGrpCod;
		
		private string _U_TipoProd;
		
		private System.Nullable<int> _U_Cultivo;
		
		private System.Nullable<decimal> _SWeight1;
		
		private System.DateTime _CreateDate;
		
		private System.Nullable<System.DateTime> _UpdateDate;
		
		private string _InvntryUom;
		
		private System.Nullable<int> _U_Envase;
		
		private System.Nullable<int> _U_Tamanio;
		
		private System.Nullable<int> _U_Color;
		
		private System.Nullable<int> _U_Etiqueta;
		
		private System.Nullable<int> _U_Presentacion;
		
		private string _NombreProduce;
		
		private string _CodeBars;
		
		private System.Nullable<int> _U_CajasNacional;
		
		private System.Nullable<int> _U_CajasExportacion;
		
		private string _U_TASAIVA;
		
		private string _CodigoProductoSAP;
		
		private System.Nullable<bool> _Inactivo;
		
		private System.Nullable<bool> _ProductoEspecial;
		
		private EntitySet<Muestra> _Muestras;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnItemCodeChanging(string value);
    partial void OnItemCodeChanged();
    partial void OnItemNameChanging(string value);
    partial void OnItemNameChanged();
    partial void OnItmsGrpCodChanging(System.Nullable<short> value);
    partial void OnItmsGrpCodChanged();
    partial void OnU_TipoProdChanging(string value);
    partial void OnU_TipoProdChanged();
    partial void OnU_CultivoChanging(System.Nullable<int> value);
    partial void OnU_CultivoChanged();
    partial void OnSWeight1Changing(System.Nullable<decimal> value);
    partial void OnSWeight1Changed();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    partial void OnUpdateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDateChanged();
    partial void OnInvntryUomChanging(string value);
    partial void OnInvntryUomChanged();
    partial void OnU_EnvaseChanging(System.Nullable<int> value);
    partial void OnU_EnvaseChanged();
    partial void OnU_TamanioChanging(System.Nullable<int> value);
    partial void OnU_TamanioChanged();
    partial void OnU_ColorChanging(System.Nullable<int> value);
    partial void OnU_ColorChanged();
    partial void OnU_EtiquetaChanging(System.Nullable<int> value);
    partial void OnU_EtiquetaChanged();
    partial void OnU_PresentacionChanging(System.Nullable<int> value);
    partial void OnU_PresentacionChanged();
    partial void OnNombreProduceChanging(string value);
    partial void OnNombreProduceChanged();
    partial void OnCodeBarsChanging(string value);
    partial void OnCodeBarsChanged();
    partial void OnU_CajasNacionalChanging(System.Nullable<int> value);
    partial void OnU_CajasNacionalChanged();
    partial void OnU_CajasExportacionChanging(System.Nullable<int> value);
    partial void OnU_CajasExportacionChanged();
    partial void OnU_TASAIVAChanging(string value);
    partial void OnU_TASAIVAChanged();
    partial void OnCodigoProductoSAPChanging(string value);
    partial void OnCodigoProductoSAPChanged();
    partial void OnInactivoChanging(System.Nullable<bool> value);
    partial void OnInactivoChanged();
    partial void OnProductoEspecialChanging(System.Nullable<bool> value);
    partial void OnProductoEspecialChanged();
    #endregion
		
		public Producto()
		{
			this._Muestras = new EntitySet<Muestra>(new Action<Muestra>(this.attach_Muestras), new Action<Muestra>(this.detach_Muestras));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemCode", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ItemCode
		{
			get
			{
				return this._ItemCode;
			}
			set
			{
				if ((this._ItemCode != value))
				{
					this.OnItemCodeChanging(value);
					this.SendPropertyChanging();
					this._ItemCode = value;
					this.SendPropertyChanged("ItemCode");
					this.OnItemCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemName", DbType="NVarChar(100)")]
		public string ItemName
		{
			get
			{
				return this._ItemName;
			}
			set
			{
				if ((this._ItemName != value))
				{
					this.OnItemNameChanging(value);
					this.SendPropertyChanging();
					this._ItemName = value;
					this.SendPropertyChanged("ItemName");
					this.OnItemNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItmsGrpCod", DbType="SmallInt")]
		public System.Nullable<short> ItmsGrpCod
		{
			get
			{
				return this._ItmsGrpCod;
			}
			set
			{
				if ((this._ItmsGrpCod != value))
				{
					this.OnItmsGrpCodChanging(value);
					this.SendPropertyChanging();
					this._ItmsGrpCod = value;
					this.SendPropertyChanged("ItmsGrpCod");
					this.OnItmsGrpCodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_TipoProd", DbType="NVarChar(MAX)")]
		public string U_TipoProd
		{
			get
			{
				return this._U_TipoProd;
			}
			set
			{
				if ((this._U_TipoProd != value))
				{
					this.OnU_TipoProdChanging(value);
					this.SendPropertyChanging();
					this._U_TipoProd = value;
					this.SendPropertyChanged("U_TipoProd");
					this.OnU_TipoProdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_Cultivo", DbType="Int")]
		public System.Nullable<int> U_Cultivo
		{
			get
			{
				return this._U_Cultivo;
			}
			set
			{
				if ((this._U_Cultivo != value))
				{
					this.OnU_CultivoChanging(value);
					this.SendPropertyChanging();
					this._U_Cultivo = value;
					this.SendPropertyChanged("U_Cultivo");
					this.OnU_CultivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SWeight1", DbType="Decimal(19,6)")]
		public System.Nullable<decimal> SWeight1
		{
			get
			{
				return this._SWeight1;
			}
			set
			{
				if ((this._SWeight1 != value))
				{
					this.OnSWeight1Changing(value);
					this.SendPropertyChanging();
					this._SWeight1 = value;
					this.SendPropertyChanged("SWeight1");
					this.OnSWeight1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this.OnUpdateDateChanging(value);
					this.SendPropertyChanging();
					this._UpdateDate = value;
					this.SendPropertyChanged("UpdateDate");
					this.OnUpdateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvntryUom", DbType="NVarChar(20)")]
		public string InvntryUom
		{
			get
			{
				return this._InvntryUom;
			}
			set
			{
				if ((this._InvntryUom != value))
				{
					this.OnInvntryUomChanging(value);
					this.SendPropertyChanging();
					this._InvntryUom = value;
					this.SendPropertyChanged("InvntryUom");
					this.OnInvntryUomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_Envase", DbType="Int")]
		public System.Nullable<int> U_Envase
		{
			get
			{
				return this._U_Envase;
			}
			set
			{
				if ((this._U_Envase != value))
				{
					this.OnU_EnvaseChanging(value);
					this.SendPropertyChanging();
					this._U_Envase = value;
					this.SendPropertyChanged("U_Envase");
					this.OnU_EnvaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_Tamanio", DbType="Int")]
		public System.Nullable<int> U_Tamanio
		{
			get
			{
				return this._U_Tamanio;
			}
			set
			{
				if ((this._U_Tamanio != value))
				{
					this.OnU_TamanioChanging(value);
					this.SendPropertyChanging();
					this._U_Tamanio = value;
					this.SendPropertyChanged("U_Tamanio");
					this.OnU_TamanioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_Color", DbType="Int")]
		public System.Nullable<int> U_Color
		{
			get
			{
				return this._U_Color;
			}
			set
			{
				if ((this._U_Color != value))
				{
					this.OnU_ColorChanging(value);
					this.SendPropertyChanging();
					this._U_Color = value;
					this.SendPropertyChanged("U_Color");
					this.OnU_ColorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_Etiqueta", DbType="Int")]
		public System.Nullable<int> U_Etiqueta
		{
			get
			{
				return this._U_Etiqueta;
			}
			set
			{
				if ((this._U_Etiqueta != value))
				{
					this.OnU_EtiquetaChanging(value);
					this.SendPropertyChanging();
					this._U_Etiqueta = value;
					this.SendPropertyChanged("U_Etiqueta");
					this.OnU_EtiquetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_Presentacion", DbType="Int")]
		public System.Nullable<int> U_Presentacion
		{
			get
			{
				return this._U_Presentacion;
			}
			set
			{
				if ((this._U_Presentacion != value))
				{
					this.OnU_PresentacionChanging(value);
					this.SendPropertyChanging();
					this._U_Presentacion = value;
					this.SendPropertyChanged("U_Presentacion");
					this.OnU_PresentacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreProduce", DbType="NVarChar(100)")]
		public string NombreProduce
		{
			get
			{
				return this._NombreProduce;
			}
			set
			{
				if ((this._NombreProduce != value))
				{
					this.OnNombreProduceChanging(value);
					this.SendPropertyChanging();
					this._NombreProduce = value;
					this.SendPropertyChanged("NombreProduce");
					this.OnNombreProduceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeBars", DbType="VarChar(16)")]
		public string CodeBars
		{
			get
			{
				return this._CodeBars;
			}
			set
			{
				if ((this._CodeBars != value))
				{
					this.OnCodeBarsChanging(value);
					this.SendPropertyChanging();
					this._CodeBars = value;
					this.SendPropertyChanged("CodeBars");
					this.OnCodeBarsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_CajasNacional", DbType="Int")]
		public System.Nullable<int> U_CajasNacional
		{
			get
			{
				return this._U_CajasNacional;
			}
			set
			{
				if ((this._U_CajasNacional != value))
				{
					this.OnU_CajasNacionalChanging(value);
					this.SendPropertyChanging();
					this._U_CajasNacional = value;
					this.SendPropertyChanged("U_CajasNacional");
					this.OnU_CajasNacionalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_CajasExportacion", DbType="Int")]
		public System.Nullable<int> U_CajasExportacion
		{
			get
			{
				return this._U_CajasExportacion;
			}
			set
			{
				if ((this._U_CajasExportacion != value))
				{
					this.OnU_CajasExportacionChanging(value);
					this.SendPropertyChanging();
					this._U_CajasExportacion = value;
					this.SendPropertyChanged("U_CajasExportacion");
					this.OnU_CajasExportacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_TASAIVA", DbType="NVarChar(200)")]
		public string U_TASAIVA
		{
			get
			{
				return this._U_TASAIVA;
			}
			set
			{
				if ((this._U_TASAIVA != value))
				{
					this.OnU_TASAIVAChanging(value);
					this.SendPropertyChanging();
					this._U_TASAIVA = value;
					this.SendPropertyChanged("U_TASAIVA");
					this.OnU_TASAIVAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoProductoSAP", DbType="NVarChar(112)")]
		public string CodigoProductoSAP
		{
			get
			{
				return this._CodigoProductoSAP;
			}
			set
			{
				if ((this._CodigoProductoSAP != value))
				{
					this.OnCodigoProductoSAPChanging(value);
					this.SendPropertyChanging();
					this._CodigoProductoSAP = value;
					this.SendPropertyChanged("CodigoProductoSAP");
					this.OnCodigoProductoSAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inactivo", DbType="Bit")]
		public System.Nullable<bool> Inactivo
		{
			get
			{
				return this._Inactivo;
			}
			set
			{
				if ((this._Inactivo != value))
				{
					this.OnInactivoChanging(value);
					this.SendPropertyChanging();
					this._Inactivo = value;
					this.SendPropertyChanged("Inactivo");
					this.OnInactivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductoEspecial", DbType="Bit")]
		public System.Nullable<bool> ProductoEspecial
		{
			get
			{
				return this._ProductoEspecial;
			}
			set
			{
				if ((this._ProductoEspecial != value))
				{
					this.OnProductoEspecialChanging(value);
					this.SendPropertyChanging();
					this._ProductoEspecial = value;
					this.SendPropertyChanged("ProductoEspecial");
					this.OnProductoEspecialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Muestra", Storage="_Muestras", ThisKey="ItemCode", OtherKey="CodigoProducto")]
		public EntitySet<Muestra> Muestras
		{
			get
			{
				return this._Muestras;
			}
			set
			{
				this._Muestras.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Muestras(Muestra entity)
		{
			this.SendPropertyChanging();
			entity.Producto = this;
		}
		
		private void detach_Muestras(Muestra entity)
		{
			this.SendPropertyChanging();
			entity.Producto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MuestraCarga")]
	public partial class MuestraCarga : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Codigo;
		
		private int _CodigoCarga;
		
		private int _CodigoMuestra;
		
		private string _CodigoHeroku;
		
		private EntityRef<Muestra> _Muestra;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoChanging(int value);
    partial void OnCodigoChanged();
    partial void OnCodigoCargaChanging(int value);
    partial void OnCodigoCargaChanged();
    partial void OnCodigoMuestraChanging(int value);
    partial void OnCodigoMuestraChanged();
    partial void OnCodigoHerokuChanging(string value);
    partial void OnCodigoHerokuChanged();
    #endregion
		
		public MuestraCarga()
		{
			this._Muestra = default(EntityRef<Muestra>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoCarga", DbType="Int NOT NULL")]
		public int CodigoCarga
		{
			get
			{
				return this._CodigoCarga;
			}
			set
			{
				if ((this._CodigoCarga != value))
				{
					this.OnCodigoCargaChanging(value);
					this.SendPropertyChanging();
					this._CodigoCarga = value;
					this.SendPropertyChanged("CodigoCarga");
					this.OnCodigoCargaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoMuestra", DbType="Int NOT NULL")]
		public int CodigoMuestra
		{
			get
			{
				return this._CodigoMuestra;
			}
			set
			{
				if ((this._CodigoMuestra != value))
				{
					if (this._Muestra.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodigoMuestraChanging(value);
					this.SendPropertyChanging();
					this._CodigoMuestra = value;
					this.SendPropertyChanged("CodigoMuestra");
					this.OnCodigoMuestraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoHeroku", DbType="NVarChar(40)")]
		public string CodigoHeroku
		{
			get
			{
				return this._CodigoHeroku;
			}
			set
			{
				if ((this._CodigoHeroku != value))
				{
					this.OnCodigoHerokuChanging(value);
					this.SendPropertyChanging();
					this._CodigoHeroku = value;
					this.SendPropertyChanged("CodigoHeroku");
					this.OnCodigoHerokuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Muestra_MuestraCarga", Storage="_Muestra", ThisKey="CodigoMuestra", OtherKey="Codigo", IsForeignKey=true)]
		public Muestra Muestra
		{
			get
			{
				return this._Muestra.Entity;
			}
			set
			{
				Muestra previousValue = this._Muestra.Entity;
				if (((previousValue != value) 
							|| (this._Muestra.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Muestra.Entity = null;
						previousValue.MuestraCargas.Remove(this);
					}
					this._Muestra.Entity = value;
					if ((value != null))
					{
						value.MuestraCargas.Add(this);
						this._CodigoMuestra = value.Codigo;
					}
					else
					{
						this._CodigoMuestra = default(int);
					}
					this.SendPropertyChanged("Muestra");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MuestraDetalleColor")]
	public partial class MuestraDetalleColor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Codigo;
		
		private int _CodigoMuestra;
		
		private int _CodigoColor;
		
		private int _Cantidad;
		
		private EntityRef<Muestra> _Muestra;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoChanging(int value);
    partial void OnCodigoChanged();
    partial void OnCodigoMuestraChanging(int value);
    partial void OnCodigoMuestraChanged();
    partial void OnCodigoColorChanging(int value);
    partial void OnCodigoColorChanged();
    partial void OnCantidadChanging(int value);
    partial void OnCantidadChanged();
    #endregion
		
		public MuestraDetalleColor()
		{
			this._Muestra = default(EntityRef<Muestra>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoMuestra", DbType="Int NOT NULL")]
		public int CodigoMuestra
		{
			get
			{
				return this._CodigoMuestra;
			}
			set
			{
				if ((this._CodigoMuestra != value))
				{
					if (this._Muestra.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodigoMuestraChanging(value);
					this.SendPropertyChanging();
					this._CodigoMuestra = value;
					this.SendPropertyChanged("CodigoMuestra");
					this.OnCodigoMuestraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoColor", DbType="Int NOT NULL")]
		public int CodigoColor
		{
			get
			{
				return this._CodigoColor;
			}
			set
			{
				if ((this._CodigoColor != value))
				{
					this.OnCodigoColorChanging(value);
					this.SendPropertyChanging();
					this._CodigoColor = value;
					this.SendPropertyChanged("CodigoColor");
					this.OnCodigoColorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int NOT NULL")]
		public int Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this.OnCantidadChanging(value);
					this.SendPropertyChanging();
					this._Cantidad = value;
					this.SendPropertyChanged("Cantidad");
					this.OnCantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Muestra_MuestraDetalleColor", Storage="_Muestra", ThisKey="CodigoMuestra", OtherKey="Codigo", IsForeignKey=true)]
		public Muestra Muestra
		{
			get
			{
				return this._Muestra.Entity;
			}
			set
			{
				Muestra previousValue = this._Muestra.Entity;
				if (((previousValue != value) 
							|| (this._Muestra.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Muestra.Entity = null;
						previousValue.MuestraDetalleColors.Remove(this);
					}
					this._Muestra.Entity = value;
					if ((value != null))
					{
						value.MuestraDetalleColors.Add(this);
						this._CodigoMuestra = value.Codigo;
					}
					else
					{
						this._CodigoMuestra = default(int);
					}
					this.SendPropertyChanged("Muestra");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TarimasCarga")]
	public partial class TarimasCarga : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodigoCarga;
		
		private int _CodigoColor;
		
		private int _NumeroTarimas;
		
		private System.Nullable<int> _CodigoRecepcion;
		
		private int _Codigo;
		
		private System.Nullable<int> _CodigoMuestra;
		
		private System.Nullable<int> _CodigoAgricultor;
		
		private EntityRef<Muestra> _Muestra;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoCargaChanging(int value);
    partial void OnCodigoCargaChanged();
    partial void OnCodigoColorChanging(int value);
    partial void OnCodigoColorChanged();
    partial void OnNumeroTarimasChanging(int value);
    partial void OnNumeroTarimasChanged();
    partial void OnCodigoRecepcionChanging(System.Nullable<int> value);
    partial void OnCodigoRecepcionChanged();
    partial void OnCodigoChanging(int value);
    partial void OnCodigoChanged();
    partial void OnCodigoMuestraChanging(System.Nullable<int> value);
    partial void OnCodigoMuestraChanged();
    partial void OnCodigoAgricultorChanging(System.Nullable<int> value);
    partial void OnCodigoAgricultorChanged();
    #endregion
		
		public TarimasCarga()
		{
			this._Muestra = default(EntityRef<Muestra>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoCarga", DbType="Int NOT NULL")]
		public int CodigoCarga
		{
			get
			{
				return this._CodigoCarga;
			}
			set
			{
				if ((this._CodigoCarga != value))
				{
					this.OnCodigoCargaChanging(value);
					this.SendPropertyChanging();
					this._CodigoCarga = value;
					this.SendPropertyChanged("CodigoCarga");
					this.OnCodigoCargaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoColor", DbType="Int NOT NULL")]
		public int CodigoColor
		{
			get
			{
				return this._CodigoColor;
			}
			set
			{
				if ((this._CodigoColor != value))
				{
					this.OnCodigoColorChanging(value);
					this.SendPropertyChanging();
					this._CodigoColor = value;
					this.SendPropertyChanged("CodigoColor");
					this.OnCodigoColorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroTarimas", DbType="Int NOT NULL")]
		public int NumeroTarimas
		{
			get
			{
				return this._NumeroTarimas;
			}
			set
			{
				if ((this._NumeroTarimas != value))
				{
					this.OnNumeroTarimasChanging(value);
					this.SendPropertyChanging();
					this._NumeroTarimas = value;
					this.SendPropertyChanged("NumeroTarimas");
					this.OnNumeroTarimasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoRecepcion", DbType="Int")]
		public System.Nullable<int> CodigoRecepcion
		{
			get
			{
				return this._CodigoRecepcion;
			}
			set
			{
				if ((this._CodigoRecepcion != value))
				{
					this.OnCodigoRecepcionChanging(value);
					this.SendPropertyChanging();
					this._CodigoRecepcion = value;
					this.SendPropertyChanged("CodigoRecepcion");
					this.OnCodigoRecepcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoMuestra", DbType="Int")]
		public System.Nullable<int> CodigoMuestra
		{
			get
			{
				return this._CodigoMuestra;
			}
			set
			{
				if ((this._CodigoMuestra != value))
				{
					if (this._Muestra.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodigoMuestraChanging(value);
					this.SendPropertyChanging();
					this._CodigoMuestra = value;
					this.SendPropertyChanged("CodigoMuestra");
					this.OnCodigoMuestraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoAgricultor", DbType="Int")]
		public System.Nullable<int> CodigoAgricultor
		{
			get
			{
				return this._CodigoAgricultor;
			}
			set
			{
				if ((this._CodigoAgricultor != value))
				{
					this.OnCodigoAgricultorChanging(value);
					this.SendPropertyChanging();
					this._CodigoAgricultor = value;
					this.SendPropertyChanged("CodigoAgricultor");
					this.OnCodigoAgricultorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Muestra_TarimasCarga", Storage="_Muestra", ThisKey="CodigoMuestra", OtherKey="Codigo", IsForeignKey=true)]
		public Muestra Muestra
		{
			get
			{
				return this._Muestra.Entity;
			}
			set
			{
				Muestra previousValue = this._Muestra.Entity;
				if (((previousValue != value) 
							|| (this._Muestra.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Muestra.Entity = null;
						previousValue.TarimasCargas.Remove(this);
					}
					this._Muestra.Entity = value;
					if ((value != null))
					{
						value.TarimasCargas.Add(this);
						this._CodigoMuestra = value.Codigo;
					}
					else
					{
						this._CodigoMuestra = default(Nullable<int>);
					}
					this.SendPropertyChanged("Muestra");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
